### PR TITLE
Provide example of how to load saved model

### PR DESCRIPTION
**Pull request by dennyglee**

### CODE REVIEW

**Review by dmatrix — CHANGES_REQUESTED** [review]
Thanks for the PR. Good idea to provide that bit of functionality to save the model both in the H5 format and MLflow flavor so that it can be accessed outside mlflow and also used to predict using keras APIs. Currently, the model is saved as part of the artifact and can be accessed via mlflow.tracking API.

One thing we want to consider before merging in reload_nn.py is the following: This is duplicate code and not necessary; instead, in reload_nn.py create a superclass of KTrain(), and use the base methods or override base methods specific to reload_nn.py. 

That way, should there be a problem or bug in the train_nn.py, we don't have to fix code in two places and we maintain modularity and maintainability. I plan to integrate this as part of mlflow-apps, and having this modular aspects lends itself in style and format. 

What do you think?

**Comment by dennyglee** [comment]
Good idea - I'll make the changes you suggest.  Meanwhile, I added to the PR the `predict_nn.py` so this way you can predict sentiment using your model.

I think I might have merged your reload_nn.py, as I see it in the repo. Later, you can file another PR to modularize it as you did with predict_nn.py. Nice!

**Review by dmatrix — APPROVED** [review]

**Review by dmatrix — APPROVED** [review]

**Comment by dmatrix** [comment]
Thanks for the PR. Adds functionality to it, and sticks with the modularity. I assume you going to do the same with the retrain_nn.py. Thanks!

**Comment by dennyglee** [comment]
Roger wilco - will do!

**Pull request merged**
